# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Abhi_locater' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Abhi_locater
  # pod 'SWRevealViewController'
    
    
  target 'Abhi_locaterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Abhi_locaterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
